[tool.poetry]
name = "Buisness cats"
version = "0.1.0"
description = "Эмуляция игры Бизнес-коты"
authors = ["AspirantDrago <sanekclubstr@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.group.dev.dependencies]
sphinx = "^8.2.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
